// A simple click-counter utility generated by Vite's default project scaffold.

export function setupCounter(element) {
  let counter = 0 // tracks the current count in memory

  // updates the DOM element's text and syncs the in-memory counter
  const setCounter = (count) => {
    counter = count
    element.innerHTML = `Count is ${counter}`
  }

  // each click increments the counter by 1
  element.addEventListener('click', () => setCounter(counter + 1))

  // initialise the display to "Count is 0" on setup
  setCounter(0)
}
